from src.vacancies import Vacancy


def get_vacancies_list(vacancies_info: list) -> list[Vacancy]:
    """
    Преобразовывает список вакансий из общего списка вакансий hh.ru в список объектов Vacancy
    """

    vacancies_list = []
    for vacancy in vacancies_info:
        vacancies_list.append(Vacancy(vacancy['name'],
                                      vacancy['url'],
                                      f'{vacancy['salary']['from'] if vacancy['salary']['from'] else '0'} - '
                                      f'{vacancy['salary']['to'] if vacancy['salary']['to'] else '0'}',
                                      vacancy['salary']['currency'],
                                      vacancy['snippet']['responsibility'],
                                      vacancy['snippet']['requirement']))

    return vacancies_list


def filter_vacancies(vacancies: list[Vacancy],
                     filter_words: list,
                     salary_range: str,
                     currency: str,
                     top_n: int) -> list[Vacancy]:
    """
    Фильтрует вакансии по ключевым словам и зарплате
    """
    salary = [int(i) for i in salary_range.split(' - ')]
    n = 0
    filtered_vacancies = []
    for vacancy in vacancies:

        if ([word for word in filter_words if word.lower() in str(vacancy.responsibility).lower().split()] != []
                or [word for word in filter_words if word.lower() in str(vacancy.requirement).lower().split()] != []):
            vacancy_salary = [int(i) for i in vacancy.salary.split(' - ')]
            if salary[0] <= vacancy_salary[0] and salary[1] >= vacancy_salary[1] and vacancy.currency == currency:
                n += 1
                filtered_vacancies.append(vacancy)
                print(vacancy)

        elif filter_words == []:
            vacancy_salary = [int(i) for i in vacancy.salary.split(' - ')]
            if salary[0] <= vacancy_salary[0] and salary[1] >= vacancy_salary[1] and vacancy.currency == currency:
                n += 1
                filtered_vacancies.append(vacancy)
                print(vacancy)

        if n == top_n:
            break

    print('_______________________')

    print(f'По Вашему запросу найдено {n} вакансий')

    return filtered_vacancies


def get_vacancies_by_salary(filtered_vacancies):
    """
    Сортирует отобранные вакансии по зарплате
    """
    vacancies_by_salary = []
    for vacancy in sorted(filtered_vacancies, key=lambda x: int(x.salary.split(' - ')[1]) if int(x.salary.split(' - ')[1]) > 0 else int(x.salary.split(' - ')[0]), reverse=True):
        vacancies_by_salary.append(vacancy)
        print(vacancy)

    return vacancies_by_salary



if __name__ == '__main__':
    data = [{'id': '106501725', 'premium': False, 'name': 'Аналитик', 'department': None, 'has_test': False, 'response_letter_required': False, 'area': {'id': '1', 'name': 'Москва', 'url': 'https://api.hh.ru/areas/1'}, 'salary': {'from': 90000, 'to': None, 'currency': 'RUR', 'gross': False}, 'type': {'id': 'open', 'name': 'Открытая'}, 'address': {'city': 'Москва', 'street': 'Переведеновский переулок', 'building': '13с4', 'lat': 55.780289, 'lng': 37.690354, 'description': None, 'raw': 'Москва, Переведеновский переулок, 13с4', 'metro': {'station_name': 'Бауманская', 'line_name': 'Арбатско-Покровская', 'station_id': '3.17', 'line_id': '3', 'lat': 55.772405, 'lng': 37.67904}, 'metro_stations': [{'station_name': 'Бауманская', 'line_name': 'Арбатско-Покровская', 'station_id': '3.17', 'line_id': '3', 'lat': 55.772405, 'lng': 37.67904}, {'station_name': 'Электрозаводская', 'line_name': 'Арбатско-Покровская', 'station_id': '3.161', 'line_id': '3', 'lat': 55.782057, 'lng': 37.7053}], 'id': '1451179'}, 'response_url': None, 'sort_point_distance': None, 'published_at': '2024-08-29T12:26:17+0300', 'created_at': '2024-08-29T12:26:17+0300', 'archived': False, 'apply_alternate_url': 'https://hh.ru/applicant/vacancy_response?vacancyId=106501725', 'branding': {'type': 'MAKEUP', 'tariff': None}, 'show_logo_in_search': True, 'insider_interview': None, 'url': 'https://api.hh.ru/vacancies/106501725?host=hh.ru', 'alternate_url': 'https://hh.ru/vacancy/106501725', 'relations': [], 'employer': {'id': '27735', 'name': 'EcoStandard group', 'url': 'https://api.hh.ru/employers/27735', 'alternate_url': 'https://hh.ru/employer/27735', 'logo_urls': {'original': 'https://img.hhcdn.ru/employer-logo-original/787783.png', '240': 'https://img.hhcdn.ru/employer-logo/3592024.png', '90': 'https://img.hhcdn.ru/employer-logo/3592023.png'}, 'vacancies_url': 'https://api.hh.ru/vacancies?employer_id=27735', 'accredited_it_employer': False, 'trusted': True}, 'snippet': {'requirement': 'Высшее техническое образование будет преимуществом. Высокий уровень владения Power BI, Excel. Знание DAX. Приветствуется знание SQL и <highlighttext>Python</highlighttext>. ', 'responsibility': 'Разработка, внедрение, поддержка отчетов на платформе Power BI. Сбор исходных данных. Взаимодействие с внутренним заказчиком. Уточнение требований к отчету. '}, 'contacts': None, 'schedule': {'id': 'remote', 'name': 'Удаленная работа'}, 'working_days': [], 'working_time_intervals': [], 'working_time_modes': [], 'accept_temporary': False, 'professional_roles': [{'id': '10', 'name': 'Аналитик'}], 'accept_incomplete_resumes': False, 'experience': {'id': 'between1And3', 'name': 'От 1 года до 3 лет'}, 'employment': {'id': 'full', 'name': 'Полная занятость'}, 'adv_response_url': None, 'is_adv_vacancy': False, 'adv_context': None},
            {'id': '106437323', 'premium': False, 'name': 'ГИС-специалист', 'department': None, 'has_test': False, 'response_letter_required': False, 'area': {'id': '1', 'name': 'Москва', 'url': 'https://api.hh.ru/areas/1'}, 'salary': {'from': None, 'to': 90000, 'currency': 'RUR', 'gross': False}, 'type': {'id': 'open', 'name': 'Открытая'}, 'address': {'city': 'Москва', 'street': '3-я Рыбинская улица', 'building': '18с2', 'lat': 55.790514, 'lng': 37.660161, 'description': None, 'raw': 'Москва, 3-я Рыбинская улица, 18с2', 'metro': None, 'metro_stations': [], 'id': '13633656'}, 'response_url': None, 'sort_point_distance': None, 'published_at': '2024-08-28T11:29:57+0300', 'created_at': '2024-08-28T11:29:57+0300', 'archived': False, 'apply_alternate_url': 'https://hh.ru/applicant/vacancy_response?vacancyId=106437323', 'show_logo_in_search': None, 'insider_interview': None, 'url': 'https://api.hh.ru/vacancies/106437323?host=hh.ru', 'alternate_url': 'https://hh.ru/vacancy/106437323', 'relations': [], 'employer': {'id': '4021702', 'name': 'Градостроительный Институт МИРПРОЕКТ', 'url': 'https://api.hh.ru/employers/4021702', 'alternate_url': 'https://hh.ru/employer/4021702', 'logo_urls': {'original': 'https://img.hhcdn.ru/employer-logo-original/1001538.jpeg', '90': 'https://img.hhcdn.ru/employer-logo/5626932.jpeg', '240': 'https://img.hhcdn.ru/employer-logo/5626933.jpeg'}, 'vacancies_url': 'https://api.hh.ru/vacancies?employer_id=4021702', 'accredited_it_employer': False, 'trusted': True}, 'snippet': {'requirement': 'Навыки работы в ПО: MapInfo, Панорамма, Adobe Photoshop, Illustrator, SketchUp, Blender, Revit. Понимание: PostgreSQL, <highlighttext>Python</highlighttext>, др. языки программирования.', 'responsibility': 'Сбор и анализ исходных картографических, градостроительных, аналитических данных. Перепроецирование данных в различные системы координат (WGS84, ГСК, МСК). '}, 'contacts': None, 'schedule': {'id': 'fullDay', 'name': 'Полный день'}, 'working_days': [], 'working_time_intervals': [], 'working_time_modes': [], 'accept_temporary': False, 'professional_roles': [{'id': '27', 'name': 'Геодезист'}], 'accept_incomplete_resumes': False, 'experience': {'id': 'between1And3', 'name': 'От 1 года до 3 лет'}, 'employment': {'id': 'full', 'name': 'Полная занятость'}, 'adv_response_url': None, 'is_adv_vacancy': False, 'adv_context': None},
            {'id': '106497337', 'premium': False, 'name': 'Аналитик второй линии поддержки', 'department': None, 'has_test': True, 'response_letter_required': False, 'area': {'id': '1', 'name': 'Москва', 'url': 'https://api.hh.ru/areas/1'}, 'salary': {'from': 100000, 'to': None, 'currency': 'RUR', 'gross': False}, 'type': {'id': 'open', 'name': 'Открытая'}, 'address': None, 'response_url': None, 'sort_point_distance': None, 'published_at': '2024-08-29T11:34:46+0300', 'created_at': '2024-08-29T11:34:46+0300', 'archived': False, 'apply_alternate_url': 'https://hh.ru/applicant/vacancy_response?vacancyId=106497337', 'branding': {'type': 'MAKEUP', 'tariff': None}, 'show_logo_in_search': True, 'insider_interview': None, 'url': 'https://api.hh.ru/vacancies/106497337?host=hh.ru', 'alternate_url': 'https://hh.ru/vacancy/106497337', 'relations': [], 'employer': {'id': '17713', 'name': 'ЮТэйр, Авиакомпания', 'url': 'https://api.hh.ru/employers/17713', 'alternate_url': 'https://hh.ru/employer/17713', 'logo_urls': {'original': 'https://img.hhcdn.ru/employer-logo-original/939772.png', '240': 'https://img.hhcdn.ru/employer-logo/4199633.png', '90': 'https://img.hhcdn.ru/employer-logo/4199632.png'}, 'vacancies_url': 'https://api.hh.ru/vacancies?employer_id=17713', 'accredited_it_employer': True, 'trusted': True}, 'snippet': {'requirement': 'Знание основ web-технологий и навыки программирования, желательно на <highlighttext>Python</highlighttext>. Опыт работы с DBeaver. Опыт работы с Postman. ', 'responsibility': 'Вести деловую переписку и писать техническую документацию. Составлять запросы к MongoDB или SQL.'}, 'contacts': None, 'schedule': {'id': 'remote', 'name': 'Удаленная работа'}, 'working_days': [], 'working_time_intervals': [], 'working_time_modes': [], 'accept_temporary': False, 'professional_roles': [{'id': '121', 'name': 'Специалист технической поддержки'}], 'accept_incomplete_resumes': False, 'experience': {'id': 'between1And3', 'name': 'От 1 года до 3 лет'}, 'employment': {'id': 'full', 'name': 'Полная занятость'}, 'adv_response_url': None, 'is_adv_vacancy': False, 'adv_context': None},
            {'id': '106047009', 'premium': False, 'name': 'Тестировщик', 'department': None, 'has_test': False, 'response_letter_required': False, 'area': {'id': '79', 'name': 'Саратов', 'url': 'https://api.hh.ru/areas/79'}, 'salary': {'from': 80000, 'to': None, 'currency': 'RUR', 'gross': True}, 'type': {'id': 'open', 'name': 'Открытая'}, 'address': {'city': 'Саратов', 'street': 'Бахметьевская улица', 'building': '34/42', 'lat': 51.525864, 'lng': 46.015652, 'description': None, 'raw': 'Саратов, Бахметьевская улица, 34/42', 'metro': None, 'metro_stations': [], 'id': '604432'}, 'response_url': None, 'sort_point_distance': None, 'published_at': '2024-08-20T11:18:49+0300', 'created_at': '2024-08-20T11:18:49+0300', 'archived': False, 'apply_alternate_url': 'https://hh.ru/applicant/vacancy_response?vacancyId=106047009', 'show_logo_in_search': None, 'insider_interview': None, 'url': 'https://api.hh.ru/vacancies/106047009?host=hh.ru', 'alternate_url': 'https://hh.ru/vacancy/106047009', 'relations': [], 'employer': {'id': '2138838', 'name': 'ЮКЕЙСОФТ', 'url': 'https://api.hh.ru/employers/2138838', 'alternate_url': 'https://hh.ru/employer/2138838', 'logo_urls': {'240': 'https://img.hhcdn.ru/employer-logo/2379621.png', '90': 'https://img.hhcdn.ru/employer-logo/2379620.png', 'original': 'https://img.hhcdn.ru/employer-logo-original/484442.png'}, 'vacancies_url': 'https://api.hh.ru/vacancies?employer_id=2138838', 'accredited_it_employer': False, 'trusted': True}, 'snippet': {'requirement': 'Работа с баг-трекинговыми системами. Знание JavaScript или <highlighttext>Python</highlighttext> для написания авто-тестов в Selenium. Будет плюсом: Опыт работы с...', 'responsibility': 'Проведение функционального, интеграционного, системного тестирования, проверка бизнес-процесса, тестирование удобства пользования. Взаимодействие с командами разработчиков.'}, 'contacts': None, 'schedule': {'id': 'fullDay', 'name': 'Полный день'}, 'working_days': [], 'working_time_intervals': [], 'working_time_modes': [], 'accept_temporary': False, 'professional_roles': [{'id': '124', 'name': 'Тестировщик'}], 'accept_incomplete_resumes': False, 'experience': {'id': 'between1And3', 'name': 'От 1 года до 3 лет'}, 'employment': {'id': 'full', 'name': 'Полная занятость'}, 'adv_response_url': None, 'is_adv_vacancy': False, 'adv_context': None},
            {'id': '106501725', 'premium': False, 'name': 'Аналитик', 'department': None, 'has_test': False, 'response_letter_required': False, 'area': {'id': '1', 'name': 'Москва', 'url': 'https://api.hh.ru/areas/1'}, 'salary': {'from': 50000, 'to': None, 'currency': 'RUR', 'gross': False}, 'type': {'id': 'open', 'name': 'Открытая'}, 'address': {'city': 'Москва', 'street': 'Переведеновский переулок', 'building': '13с4', 'lat': 55.780289, 'lng': 37.690354, 'description': None, 'raw': 'Москва, Переведеновский переулок, 13с4', 'metro': {'station_name': 'Бауманская', 'line_name': 'Арбатско-Покровская', 'station_id': '3.17', 'line_id': '3', 'lat': 55.772405, 'lng': 37.67904}, 'metro_stations': [{'station_name': 'Бауманская', 'line_name': 'Арбатско-Покровская', 'station_id': '3.17', 'line_id': '3', 'lat': 55.772405, 'lng': 37.67904}, {'station_name': 'Электрозаводская', 'line_name': 'Арбатско-Покровская', 'station_id': '3.161', 'line_id': '3', 'lat': 55.782057, 'lng': 37.7053}], 'id': '1451179'}, 'response_url': None, 'sort_point_distance': None, 'published_at': '2024-08-29T12:26:17+0300', 'created_at': '2024-08-29T12:26:17+0300', 'archived': False, 'apply_alternate_url': 'https://hh.ru/applicant/vacancy_response?vacancyId=106501725', 'branding': {'type': 'MAKEUP', 'tariff': None}, 'show_logo_in_search': True, 'insider_interview': None, 'url': 'https://api.hh.ru/vacancies/106501725?host=hh.ru', 'alternate_url': 'https://hh.ru/vacancy/106501725', 'relations': [], 'employer': {'id': '27735', 'name': 'EcoStandard group', 'url': 'https://api.hh.ru/employers/27735', 'alternate_url': 'https://hh.ru/employer/27735', 'logo_urls': {'original': 'https://img.hhcdn.ru/employer-logo-original/787783.png', '240': 'https://img.hhcdn.ru/employer-logo/3592024.png', '90': 'https://img.hhcdn.ru/employer-logo/3592023.png'}, 'vacancies_url': 'https://api.hh.ru/vacancies?employer_id=27735', 'accredited_it_employer': False, 'trusted': True}, 'snippet': {'requirement': 'Высшее техническое образование будет преимуществом. Высокий уровень владения Power BI, Excel. Знание DAX. Приветствуется знание SQL и <highlighttext>Python</highlighttext>. ', 'responsibility': 'Разработка, внедрение, поддержка отчетов на платформе Power BI. Сбор исходных данных. Взаимодействие с внутренним заказчиком. Уточнение требований к отчету. '}, 'contacts': None, 'schedule': {'id': 'remote', 'name': 'Удаленная работа'}, 'working_days': [], 'working_time_intervals': [], 'working_time_modes': [], 'accept_temporary': False, 'professional_roles': [{'id': '10', 'name': 'Аналитик'}], 'accept_incomplete_resumes': False, 'experience': {'id': 'between1And3', 'name': 'От 1 года до 3 лет'}, 'employment': {'id': 'full', 'name': 'Полная занятость'}, 'adv_response_url': None, 'is_adv_vacancy': False, 'adv_context': None},
            {'id': '106437323', 'premium': False, 'name': 'ГИС-специалист', 'department': None, 'has_test': False, 'response_letter_required': False, 'area': {'id': '1', 'name': 'Москва', 'url': 'https://api.hh.ru/areas/1'}, 'salary': {'from': None, 'to': 50000, 'currency': 'RUR', 'gross': False}, 'type': {'id': 'open', 'name': 'Открытая'}, 'address': {'city': 'Москва', 'street': '3-я Рыбинская улица', 'building': '18с2', 'lat': 55.790514, 'lng': 37.660161, 'description': None, 'raw': 'Москва, 3-я Рыбинская улица, 18с2', 'metro': None, 'metro_stations': [], 'id': '13633656'}, 'response_url': None, 'sort_point_distance': None, 'published_at': '2024-08-28T11:29:57+0300', 'created_at': '2024-08-28T11:29:57+0300', 'archived': False, 'apply_alternate_url': 'https://hh.ru/applicant/vacancy_response?vacancyId=106437323', 'show_logo_in_search': None, 'insider_interview': None, 'url': 'https://api.hh.ru/vacancies/106437323?host=hh.ru', 'alternate_url': 'https://hh.ru/vacancy/106437323', 'relations': [], 'employer': {'id': '4021702', 'name': 'Градостроительный Институт МИРПРОЕКТ', 'url': 'https://api.hh.ru/employers/4021702', 'alternate_url': 'https://hh.ru/employer/4021702', 'logo_urls': {'original': 'https://img.hhcdn.ru/employer-logo-original/1001538.jpeg', '90': 'https://img.hhcdn.ru/employer-logo/5626932.jpeg', '240': 'https://img.hhcdn.ru/employer-logo/5626933.jpeg'}, 'vacancies_url': 'https://api.hh.ru/vacancies?employer_id=4021702', 'accredited_it_employer': False, 'trusted': True}, 'snippet': {'requirement': 'Навыки работы в ПО: MapInfo, Панорамма, Adobe Photoshop, Illustrator, SketchUp, Blender, Revit. Понимание: PostgreSQL, <highlighttext>Python</highlighttext>, др. языки программирования.', 'responsibility': 'Сбор и анализ исходных картографических, градостроительных, аналитических данных. Перепроецирование данных в различные системы координат (WGS84, ГСК, МСК). '}, 'contacts': None, 'schedule': {'id': 'fullDay', 'name': 'Полный день'}, 'working_days': [], 'working_time_intervals': [], 'working_time_modes': [], 'accept_temporary': False, 'professional_roles': [{'id': '27', 'name': 'Геодезист'}], 'accept_incomplete_resumes': False, 'experience': {'id': 'between1And3', 'name': 'От 1 года до 3 лет'}, 'employment': {'id': 'full', 'name': 'Полная занятость'}, 'adv_response_url': None, 'is_adv_vacancy': False, 'adv_context': None},
            {'id': '106497337', 'premium': False, 'name': 'Аналитик второй линии поддержки', 'department': None, 'has_test': True, 'response_letter_required': False, 'area': {'id': '1', 'name': 'Москва', 'url': 'https://api.hh.ru/areas/1'}, 'salary': {'from': 1000000, 'to': None, 'currency': 'RUR', 'gross': False}, 'type': {'id': 'open', 'name': 'Открытая'}, 'address': None, 'response_url': None, 'sort_point_distance': None, 'published_at': '2024-08-29T11:34:46+0300', 'created_at': '2024-08-29T11:34:46+0300', 'archived': False, 'apply_alternate_url': 'https://hh.ru/applicant/vacancy_response?vacancyId=106497337', 'branding': {'type': 'MAKEUP', 'tariff': None}, 'show_logo_in_search': True, 'insider_interview': None, 'url': 'https://api.hh.ru/vacancies/106497337?host=hh.ru', 'alternate_url': 'https://hh.ru/vacancy/106497337', 'relations': [], 'employer': {'id': '17713', 'name': 'ЮТэйр, Авиакомпания', 'url': 'https://api.hh.ru/employers/17713', 'alternate_url': 'https://hh.ru/employer/17713', 'logo_urls': {'original': 'https://img.hhcdn.ru/employer-logo-original/939772.png', '240': 'https://img.hhcdn.ru/employer-logo/4199633.png', '90': 'https://img.hhcdn.ru/employer-logo/4199632.png'}, 'vacancies_url': 'https://api.hh.ru/vacancies?employer_id=17713', 'accredited_it_employer': True, 'trusted': True}, 'snippet': {'requirement': 'Знание основ web-технологий и навыки программирования, желательно на <highlighttext>Python</highlighttext>. Опыт работы с DBeaver. Опыт работы с Postman. ', 'responsibility': 'Вести деловую переписку и писать техническую документацию. Составлять запросы к MongoDB или SQL.'}, 'contacts': None, 'schedule': {'id': 'remote', 'name': 'Удаленная работа'}, 'working_days': [], 'working_time_intervals': [], 'working_time_modes': [], 'accept_temporary': False, 'professional_roles': [{'id': '121', 'name': 'Специалист технической поддержки'}], 'accept_incomplete_resumes': False, 'experience': {'id': 'between1And3', 'name': 'От 1 года до 3 лет'}, 'employment': {'id': 'full', 'name': 'Полная занятость'}, 'adv_response_url': None, 'is_adv_vacancy': False, 'adv_context': None},
            ]
    vacancies_list = get_vacancies_list(data)
    print(vacancies_list)
    filtered_vacancies = filter_vacancies(vacancies_list, ['SQL'], '90000 - 100000', 'RUR', 5)
    print(filtered_vacancies)
    print(get_vacancies_by_salary(filtered_vacancies))
